### ISSUE TITLE
`vote` error

### ISSUE THREAD

**Issue by popop098** [gunyu1019/DBSkr-py#4]
## Describe the bug**<br/>
```py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\pubg_tracker\venv\lib\site-packages\jishaku\features\python.py", line 145, in jsk_python
    async for send, result in AsyncSender(executor):
  File "C:\Users\Administrator\Desktop\pubg_tracker\venv\lib\site-packages\jishaku\functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "C:\Users\Administrator\Desktop\pubg_tracker\venv\lib\site-packages\jishaku\repl\compilation.py", line 140, in traverse
    async for send, result in AsyncSender(func(*self.args)):
  File "C:\Users\Administrator\Desktop\pubg_tracker\venv\lib\site-packages\jishaku\functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 11, in _repl_coroutine
    await Bot.vote(_ctx.author.id)
  File "C:\Users\Administrator\Desktop\pubg_tracker\venv\lib\site-packages\DBSkr\client.py", line 188, in vote
    return await self.http.vote(bot_id=self.client.user.id, user_id=user_id, web_type=web_type)
  File "C:\Users\Administrator\Desktop\pubg_tracker\venv\lib\site-packages\DBSkr\https.py", line 158, in vote
    kbots = await self.koreanbots_http.vote(bot_id=bot_id, user_id=user_id)
  File "C:\Users\Administrator\Desktop\pubg_tracker\venv\lib\site-packages\DBSkr\koreanbots\https.py", line 201, in vote
    result = await self.requests.get(path=path, query=data)
TypeError: _request() got an unexpected keyword argument 'query'
```

## To Reproduce<br/>
Steps to reproduce the behavior: 투표여부 확인할때 발생함

**Comment by gunyu1019** [comment]
해당 부분에 대해선 원인을 조사하고 있습니다. 양해 부탁드립니다 :(
